spring:
  application:
    name: product-service
  datasource:
    url: jdbc:oracle:thin:@localhost:1521:xe
    username: PRODUCT
    password: PRODUCT
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect

server:
  port: 8004
  servlet:
    context-path: /product-api

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
